#!/usr/bin/env bash
# Builds wayclick-<version>-1-any.pkg.tar.zst into dist/.
#
# Assembles the package directly with bsdtar, the same way build-deb.sh does,
# so it also builds on a non-Arch machine (makepkg only runs on Arch). The
# result is a normal pacman package: install it with `pacman -U`.
set -euo pipefail
cd "$(dirname "$0")/.."
VERSION=$(grep -oP '^VERSION = "\K[^"]+' wayclick.py)
REL=1
ROOT=$(mktemp -d)
trap 'rm -rf "$ROOT"' EXIT

install -Dpm 0755 wayclick.py "$ROOT/usr/share/wayclick/wayclick.py"
install -d "$ROOT/usr/bin"
cat > "$ROOT/usr/bin/wayclick" <<'LAUNCH'
#!/usr/bin/env bash
exec python3 /usr/share/wayclick/wayclick.py "$@"
LAUNCH
chmod 0755 "$ROOT/usr/bin/wayclick"
install -Dpm 0644 packaging/wayclick.desktop "$ROOT/usr/share/applications/wayclick.desktop"
install -Dpm 0644 packaging/wayclick.svg "$ROOT/usr/share/icons/hicolor/scalable/apps/wayclick.svg"
install -Dpm 0644 packaging/99-wayclick-uinput.rules "$ROOT/usr/lib/udev/rules.d/99-wayclick-uinput.rules"
install -Dpm 0644 packaging/uinput.conf "$ROOT/usr/lib/modules-load.d/wayclick-uinput.conf"
install -Dpm 0644 LICENSE "$ROOT/usr/share/licenses/wayclick/LICENSE"
install -Dpm 0644 README.md "$ROOT/usr/share/doc/wayclick/README.md"
install -Dpm 0644 README.pt-BR.md "$ROOT/usr/share/doc/wayclick/README.pt-BR.md"
install -Dpm 0644 packaging/wayclick.install "$ROOT/.INSTALL"

SIZE=$(du -sb --exclude=.INSTALL "$ROOT" | cut -f1)
cat > "$ROOT/.PKGINFO" <<INFO
# Generated by packaging/build-pacman.sh
pkgname = wayclick
pkgbase = wayclick
pkgver = $VERSION-$REL
pkgdesc = Autoclicker for Wayland, using /dev/uinput
url = https://github.com/gabrielmf1998/WayClick
builddate = $(date +%s)
packager = gabrielmf1998 <noreply@github.com>
size = $SIZE
arch = any
license = MIT
depend = python
depend = pyside6
INFO

# .MTREE: o índice de integridade que o pacman confere na instalação
# uid/gid 0: o pacman aplica a propriedade do mtree, e pacote do Arch é root
( cd "$ROOT" && bsdtar -czf .MTREE --format=mtree --uid 0 --gid 0 \
    --uname root --gname root \
    --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
    .PKGINFO .INSTALL usr )

mkdir -p dist
OUT="$PWD/dist/wayclick-$VERSION-$REL-any.pkg.tar.zst"
# .PKGINFO tem que ser o primeiro membro do arquivo
( cd "$ROOT" && bsdtar --zstd -cf "$OUT" --uid 0 --gid 0 --uname root \
    --gname root .PKGINFO .MTREE .INSTALL usr )
echo "built: $OUT"
